### ISSUE TITLE
Does '=' have a special meaning?

### ISSUE THREAD

**Issue by magnumripper** [teeshop/rexgen#10]
See https://github.com/magnumripper/JohnTheRipper/issues/1064
```
$ rexgen/rexgen '(f|\|x|ph)'
f
|x   <-- expected
ph

$ rexgen/rexgen '(f|\|=|ph)'
f
|   <-- unexpected, missing =
ph

$ rexgen/rexgen '(f|\|\=|ph)'
f
|=
ph
```
Why do we have to escape the `=` to get it emitted?

**Comment by teeshop** [comment]
I already had a character class SPECIAL in my lexer, but I forgot to tell him what to do with special characters...

Regards, Jan
