### ISSUE TITLE
build, install and clean should be seperated

### ISSUE THREAD

**Issue by nu11nu11** [teeshop/rexgen#18]
Hi,

as of now, rexgen will be built and installed in one shot. Users might not want to go for an install but just have the libs and binaries built.

I therefore suggest to seperate build, install and clean from each other.

Thanks!
-- nu11

**Comment by teeshop** [comment]
you can run `build.sh` if you only want rexgen to be built, but not installed. This creates the build directory and compiles rexgen into it.

Regards, jan
