### ISSUE TITLE
 librexgen.so.1.2: cannot open shared object file

### ISSUE THREAD

**Issue by ironsf** [teeshop/rexgen#21]
build on linux mint 17 qiana. 
but when i am trying to run rexgen, i got this error:
rexgen: error while loading shared libraries: librexgen.so.1.2: cannot open shared object file: No such file or directory

**Comment by thereisnosec** [comment]
same here. Build on latest Arch packages.

**Comment by teeshop** [comment]
this is not a rexgen issue, but rexgen could be more verbose regarding the execution and configuration of ldconfig... (should be changed in src/librexgen/CMakeLists.txt)
