### ISSUE TITLE
lua support failed compile in Debian stable

### ISSUE THREAD

**Issue by gituser934992** [teeshop/rexgen#38]
/rexgen$ ./build.sh -p -l

/rexgen/src/librexgen/lua/librexgen_lua.cpp: In function ‘int rexgen_value(lua_State*, const Iterator*)’:
/rexgen/src/librexgen/lua/librexgen_lua.cpp:84:24: error: ‘class SimpleString’ has no member named ‘to_binary_string’
     size_t bytes = str.to_binary_string(buffer, buffer_size);
                        ^
librexgen/lua/CMakeFiles/librexgen-lua.dir/build.make:54: recipe for target 'librexgen/lua/CMakeFiles/librexgen-lua.dir/librexgen_lua.cpp.o' failed
make[2]: *** [librexgen/lua/CMakeFiles/librexgen-lua.dir/librexgen_lua.cpp.o] Error 1
CMakeFiles/Makefile2:193: recipe for target 'librexgen/lua/CMakeFiles/librexgen-lua.dir/all' failed
make[1]: *** [librexgen/lua/CMakeFiles/librexgen-lua.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2

/rexgen$ dpkg -l liblua*

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  liblua5.2-0:am 5.2.3-1.1    amd64        Shared library for the Lua interp
ii  liblua5.2-dev: 5.2.3-1.1    amd64        Development files for the Lua lan

**Comment by teeshop** [comment]
This issue has been fixed as of 1.4.1
