### ISSUE TITLE
install.sh shouldn't call build.sh

### ISSUE THREAD

**Issue by frank-dittrich** [teeshop/rexgen#4]
Background:
librexgen can be built as a regular user, which is good. You need root privileges just for installation.
But if you run ./install.sh, root will repeat the build, resulting in a build subdirectory owned by root, so that a regular user cannot build librexgen.
IMHO, it is better to allow installation without the need to rebuild everything.

**Comment by teeshop** [comment]
Hi, I changed the install scripts a little bit. install.sh still calls build.sh, but I extracted the cleaning stuff to clean.sh. So, now install.sh makes sure that rexgen is being build, but does not enforce the build process anymore.

In the long run, I think a simple script with "build", "install" and "clean" parameter are better...
