### ISSUE TITLE
? doesn't work

### ISSUE THREAD

**Issue by jackwasey** [teeshop/rexgen#49]
version 2.0.7

```
rexgen "aa?"
aa
```
I expected:
```
a
aa
```

however,
```
rexgen "aa{0,1}"
a
aa
```
works fine.

Thanks.

**Comment by teeshop** [comment]
that should be working. can you give it a try?

**Comment by jackwasey** [comment]
Will give it a go. Thanks!

**Comment by teeshop** [comment]
However, please create additional issues if you miss some functionality. I didn't have you your use case in mind when writing this tool, so it would be kind if you helped me to align rexgen to real-world use cases ;-)

Regards, Jan
